#### 여러가지 pytorch함수

In [3]:
import torch
import torch.nn as nn 

Upsample 

In [2]:
input = torch.arange(1,5,dtype=torch.float32).view(1,1,2,2)

print('input :',input)
print('input shape :',input.shape)

input : tensor([[[[1., 2.],
          [3., 4.]]]])
input shape : torch.Size([1, 1, 2, 2])


In [8]:
upsampled1 = nn.Upsample(scale_factor=2,mode='bilinear')
u1 = upsampled1(input)
print("u1 :",u1)
print('u1.shape :',u1.shape)

u1 : tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])
u1.shape : torch.Size([1, 1, 4, 4])


In [10]:
nums = torch.arange(9)
print(nums)
print('nums shape :',nums.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
nums shape : torch.Size([9])


In [12]:
#torch tensor를 numpy로 타입 변환 
numpyed = nums.numpy()
print(numpyed)
print(numpyed.shape)
print(type(numpyed))

[0 1 2 3 4 5 6 7 8]
(9,)
<class 'numpy.ndarray'>


In [18]:
print(type(nums))
print(nums.shape)
print(nums.view(3,-1))


permuted1 = nums.view(1,3,3)
print(permuted1.shape)
print(permuted1)
print(permuted1.permute(1,0,2))


<class 'torch.Tensor'>
torch.Size([9])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([1, 3, 3])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]],

        [[6, 7, 8]]])


In [19]:
torch.tensor([
    [1,2],
    [3,4.]
])

tensor([[1., 2.],
        [3., 4.]])

In [21]:
#arange를 이용한 1차원 텐서 
oned = torch.arange(0,10)
print(oned)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [25]:
zeros = torch.zeros([3,5])
print(zeros)
print(zeros.shape)
unsqueed1 = zeros.unsqueeze(2)
print(unsqueed1.shape)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])
torch.Size([3, 5, 1])


In [1]:
import torch

In [2]:
test1 = torch.rand(5,1,3,224,224)

In [3]:
tensor_size = test1.size()
print("tensor_size ",tensor_size)

tensor_size  torch.Size([5, 1, 3, 224, 224])


In [5]:
resized = test1.view(-1,1,tensor_size[-3],tensor_size[-2],tensor_size[-1])
print("resized :",resized.shape)

resized : torch.Size([5, 1, 3, 224, 224])


In [6]:
test2 = torch.rand(15,1,3,114,114)
tensor_size2 = test2.size()
resized2 = test2.view(-1,1,tensor_size2[-3],tensor_size2[-2],tensor_size2[-1])
print("resized2 :",resized2.shape)

resized2 : torch.Size([15, 1, 3, 114, 114])


In [7]:
print(resized2.shape[0])

15


In [8]:
import numpy as np

In [25]:
max_frame = 10
slice_framepos=5
if max_frame < resized2.shape[0]:
    if slice_framepos==0:
        res = resized2[:max_frame, ...]
    elif slice_framepos==1:
        res = resized2[-max_frame, ...]
    else:
        sample_indx = np.linspace(0,resized2.shape[0]-1, num=max_frame,dtype=int)
        res = resized2[sample_indx,...]
else:
    res = resized2

In [26]:
print(res.shape)
print(sample_indx)

torch.Size([10, 1, 3, 114, 114])
[ 0  1  3  4  6  7  9 10 12 14]
