In [1]:
import torch

In [9]:
x = torch.ones([2,2],requires_grad=True)
y = x+2
z = y*y 
z

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)

In [10]:
out = z.mean()
out

tensor(9., grad_fn=<MeanBackward0>)

In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


벡터-제이코비언 곱의 예제

In [13]:
x = torch.randn(3,requires_grad=True)
y = x*2 

while y.data.norm() < 1000:
    y = y*2 
print(y)

tensor([  869.3555, -1196.8870,   133.2522], grad_fn=<MulBackward0>)


torch.autograd는 모든 제이코비언을 직접 게산할 수 없습니다. 

하지만 벡터-제이코비언 곱은 backward에 해당 벡터를 인자로 주어서, 간단히 벡터-제이코비언 곱을 구할 수 있습니다.

In [14]:
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float)

In [15]:
y.backward(v)

print(x.grad)

tensor([ 102.4000, 1024.0000,    1.0240])
