#### 파이토치에 대해서.

Tensor : 넘파이의 ndarray와 비슷합니다.

In [24]:
from __future__ import print_function
import torch

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="6"

In [3]:
x = torch.empty(5,3)
x

tensor([[0.0000e+00, 4.1216e+21, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 5.2899e-08],
        [1.0548e-08, 4.1299e-08, 2.0914e+20],
        [3.3278e+21, 3.2944e-09, 4.3960e-05],
        [1.3236e+22, 1.6916e-04, 1.3346e+19]])

초기화되지 않은 행렬이 선언되었지만, 그때 메모리에 할당된 어떤 값이든지 초기값으로 세팅합니다.

임의로 초기화된 행렬ㅇ

In [4]:
y = torch.rand(5,3)
y

tensor([[0.4503, 0.4089, 0.3094],
        [0.9494, 0.9044, 0.4554],
        [0.6286, 0.4796, 0.0545],
        [0.8756, 0.1966, 0.5470],
        [0.9417, 0.6155, 0.1789]])

데이터 타입이 long인 0 행렬

In [7]:
z = torch.zeros([5,3],dtype=float)
zz = torch.zeros(5,3,dtype=float)

In [8]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [9]:
zz

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [10]:
x

tensor([[0.0000e+00, 4.1216e+21, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 5.2899e-08],
        [1.0548e-08, 4.1299e-08, 2.0914e+20],
        [3.3278e+21, 3.2944e-09, 4.3960e-05],
        [1.3236e+22, 1.6916e-04, 1.3346e+19]])

In [11]:
print(x+y)

tensor([[4.5028e-01, 4.1216e+21, 1.8788e+31],
        [1.7220e+22, 9.0437e-01, 4.5545e-01],
        [6.2856e-01, 4.7961e-01, 2.0914e+20],
        [3.3278e+21, 1.9663e-01, 5.4700e-01],
        [1.3236e+22, 6.1569e-01, 1.3346e+19]])


크기 조정 : tensor를 resize/reshape 하고 싶으면 torch.view를 사용할 수 있습니다.

In [13]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # 8이 있으니 -1
zz = x.reshape(-1,16)

print(x.shape,y.shape,z.shape,zz.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([1, 16])


Numpy로 변환

Torch Tensor를 Numpy 배열로 변환하거나 그 반대도 가능합니다.

Torch Tensor를 Numpy로 변환

In [19]:
a = torch.ones(5,dtype=int)
b = a.numpy()


In [21]:
print(a,b)
print(b,type(b))

tensor([1, 1, 1, 1, 1]) [1 1 1 1 1]
[1 1 1 1 1] <class 'numpy.ndarray'>


Numpy array를 Torch Tensor로 변경하기

np array를 변경하면 Torch Tensor의 값도 자동으로 변경될까요?

In [22]:
import numpy as np 

a = np.ones(5)
b = torch.from_numpy(a)

np.add(a,1,out=a)
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA Tensors

Tensor는 .to 메서드를 사용하여 어떤 장치로 이동될 수 있습니다.

In [25]:
if torch.cuda.is_available():
    device = torch.device('cuda') #CUDA 장치 객체를 생성
    y = torch.ones_like(x,device=device) #CUDA device를 가지고 tensor 생성
    x = x.to(device)

    z = x+y 
    print(z)
    print(z.to('cpu',torch.double))

tensor([[ 3.2012,  1.3847,  0.7403,  2.5537],
        [-1.0819,  0.6926, -0.3654,  1.0392],
        [ 2.3029,  0.6552,  1.1707,  1.7872],
        [ 0.7642,  0.9683,  2.1408,  0.7007]], device='cuda:0')
tensor([[ 3.2012,  1.3847,  0.7403,  2.5537],
        [-1.0819,  0.6926, -0.3654,  1.0392],
        [ 2.3029,  0.6552,  1.1707,  1.7872],
        [ 0.7642,  0.9683,  2.1408,  0.7007]], dtype=torch.float64)
