#### Pytorch 실습 

Numpy array, torch.tensor 조작하기

In [69]:
import numpy as np 
import torch
from collections import deque

torch.tensor에서 주로 쓰는 자료형..

FloatTensor : 32비트 float형 


DoubleTensor : 64비트 float형 


ByteTensor : 8비트 integer형 True / False 


LongTensor : 64비트 주로 integer형을 다룰 때에 사용합니다.

In [7]:
seed = np.array([1.,2.,3.,4.])

In [12]:
f_tensor = torch.FloatTensor(seed)
print(f_tensor)

d_tensor = torch.DoubleTensor(seed)
print(d_tensor)

b_tensor = torch.ByteTensor(seed)
print(b_tensor)

l_tensor = torch.LongTensor(seed)
print(l_tensor)

bool_tensor = torch.ByteTensor([True,False])
print(bool_tensor)

tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([1, 2, 3, 4], dtype=torch.uint8)
tensor([1, 2, 3, 4])
tensor([1, 0], dtype=torch.uint8)


사칙 연산

element-wise한 연산을 하거나, 내장 module - add,sub 등을 사용할 수도 있습니다.

In [19]:
E = torch.tensor([[1,0],[0,1]])

In [21]:
tensor1 = torch.tensor([[3,5],[6,1]])
tensor2 = torch.tensor([[8,1],[1,1]])

In [30]:
res = torch.tensor(np.dot(E,tensor1))


print(res)
print(tensor1)

flag=1
for x in range(len(res)):
    for y in range(len(res[x])):
        if res[x][y]==tensor1[x][y]:
            continue 
        else:
            flag=0
            break 
    if flag==0:
        break 

if flag==1:
    print("the two tensor is same")
else:
    print("The two tensor is different each other")

tensor([[3, 5],
        [6, 1]])
tensor([[3, 5],
        [6, 1]])
the two tensor is same


In [33]:
addres = tensor1+tensor2 

print(addres)

address = tensor1.add(tensor2)

print(address)

tensor([[11,  6],
        [ 7,  2]])
tensor([[11,  6],
        [ 7,  2]])


곱셈의 경우 조금 사정이 다릅니다.

1. element-wise한 곱셈

In [34]:
mulress = tensor1 * tensor2 

print(mulress)

tensor([[24,  5],
        [ 6,  1]])


2. 고등학교 때 배운 행렬 곱셈

In [40]:
tensor1 = torch.tensor([[3.,5.],[6.,1.]])
tensor2 = torch.tensor([[8.,1.],[1.,1.]])

matrixres = np.dot(tensor1,tensor2)
print(matrixres)

[[29.  8.]
 [49.  7.]]


평균 계산

In [165]:
tensor1 = torch.tensor([[3.,5.],[6.,1.]])
tensor2 = torch.tensor([[3,5],[6,1]])
print("{:.2f}".format(tensor1.mean()))

print("{:.2d}".format(tensor2.mean()))

3.75


RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

- dim = 0 으로 설정하면 n차원 행렬의 세로 행에 대한 평균만을 구하고

- dim = 1 으로 설정하면 n차원 행렬의 가로 열에 대한 평균을 구합니다.

In [51]:
print("{:.2f}".format(tensor1.mean(dim=0)))

TypeError: unsupported format string passed to Tensor.__format__

In [53]:
print("{}".format(tensor1.mean(dim=0)))
print("{}".format(tensor2.mean(dim=1)))
print("{}".format(tensor1.mean(dim=0)))
print("{}".format(tensor2.mean(dim=1)))

tensor([4.5000, 3.0000])
tensor([4.5000, 1.0000])
tensor([4.5000, 3.0000])
tensor([4.5000, 1.0000])


In [55]:
tensor3 = torch.tensor([[1,2],[3,4]])
print("{:.2f}".format(tensor3.mean()))

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

기본적인 사칙연산, dfs, 합 대소 비교, 출력에서의 부모, 자식 구분을 수행하는 클래스를 구현하세요.

In [80]:
class basic:

    def __init__(self,tensor1,tensor2):
        self.tensor1 = tensor1 
        self.tensor2 = tensor2 
        print("basic parents class is called")
        #self.basic_tensor = torch.tensor(self.tensor1+1)
    
    def show(self):
        print("basic : tensor showing :")
        print('tensor1')
        for x in range(len(self.tensor1)):
            for y in range(len(self.tensor1[x])):
                print(self.tensor1[x][y],end=' ')
            print()
        
        print()
        print('tensor2')
        for x in range(len(self.tensor2)):
            for y in range(len(self.tensor2[x])):
                print(self.tensor2[x][y],end=' ')
            print()
        print()

    

In [156]:
class specific(basic):
    #private
    queue = deque()

    #일단 specific에 대한 생성자를 먼저 생성해야겠지?
    def __init__(self,**kwargs):
        self.tensor1 = kwargs['tensor1']
        self.tensor2 = kwargs['tensor2']

        self.map = kwargs['map']
        self.visited = [[False]*len(kwargs['map'][0]) for _ in range(len(kwargs['map']))]
        print("specific class is called")

        #basic 클래스가 만들어질 때 자동대로 basic에 대한 self가 만들어지기 때문에
        # 인자로 self.tensor1,self.tensor2만 보내주면 됩니다.  
        super(specific,self).__init__(self.tensor1,self.tensor2)


    def torch_bfs(self):
        
        
        dx = [1,-1,0,0]
        dy = [0,0,1,-1]

        self.queue.append([0,0])
        self.visited[0][0]=True
        cnt=0 
        while self.queue:
            
            curx,cury = self.queue.popleft()

            for i in range(4):
                nx = curx+dx[i]
                ny = cury+dy[i]

                if nx>=0 and nx<len(self.map) and ny>=0 and ny<len(self.map[0]):
                    if self.visited[nx][ny]==False and self.map[nx][ny]==0:
                        self.visited[nx][ny]=True 
                        self.queue.append([nx,ny])
                        cnt+=1
        
        return cnt 

    
    #두 행렬에 대한 dot product를 리턴 
    def torch_dot(self):
        res = torch.tensor(np.dot(tensor1,tensor2))

        return res 
    
    def torch_multiple(self):
        res = torch.tensor(tensor1 * tensor2)
        return res
            



In [157]:
mapp = np.array([ [0,1,1,1,1], [0,0,0,1,0],[1,0,0,1,1],[1,0,0,0,0]])
print(len(mapp))
print(len(mapp[0]))

4
5


In [158]:
x  = torch.tensor([[1.,2.],[7.,3.]])
y = torch.tensor([[6.,3.],[8.,2.]])

mapp = torch.tensor([ [0,1,1,1,1], [0,0,0,1,0],[1,0,0,1,1],[1,0,0,0,0]])



In [159]:
specific_ = specific(tensor1 = x, tensor2 = y, map=mapp)


specific class is called
basic parents class is called


In [160]:
specific_.show()

basic : tensor showing :
tensor1
tensor(1.) tensor(2.) 
tensor(7.) tensor(3.) 

tensor2
tensor(6.) tensor(3.) 
tensor(8.) tensor(2.) 



In [161]:
specific_.torch_bfs()

9

In [162]:
specific_.torch_dot()

tensor([[8., 1.],
        [1., 1.]], dtype=torch.float64)

In [163]:
specific_.torch_multiple()

/tmp/ipykernel_66196/987865683.py:52: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  res = torch.tensor(tensor1 * tensor2)


tensor([[8., 0.],
        [0., 1.]])