Linear Regression

In [1]:
import torch 
import numpy as np 
import pandas as pd

In [2]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

2. 가설 수립

선형 회귀의 가설 : 1차원 방정식 + y절편 

H(x) = Wx + b



파이토치로 선형 회귀 구현하기

1. 기본 세팅

In [3]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

In [4]:
torch.manual_seed(1)

2. 변수 선언

In [5]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [6]:
print(x_train.shape)
print(y_train.shape)

torch.Size([3, 1])
torch.Size([3, 1])


3. 가중치와 편향의 초기화 

선형 회귀란, 학습 데이터와 가장 잘 맞는 하나의 직선을 긋는 일.

그 직선을 정의 하는 W,b를 구하기.

In [7]:
Weight = torch.zeros(1,requires_grad=True)
print(Weight)

tensor([0.], requires_grad=True)


가중치 Weight는 0으로 초기화된, 크기 1짜리 1차원 벡터입니다. 

requires_grad = True : 변수가 학습을 통해 계속 변화

In [8]:
bias  = torch.zeros(1,requires_grad=True)
print(bias)

tensor([0.], requires_grad=True)


4. 가설 세우기

- 파이토치 코드 상으로 직선의 방정식에 해당되는 가설을 선언합니다.

In [9]:
hypothesis = x_train * Weight + bias 
print(hypothesis)
print(hypothesis.shape)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
torch.Size([3, 1])


5. 비용 함수 선언하기 

In [10]:
cost = torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


6. 경사 하강법 구현

SGD : Stochastic Gradient Descent 

In [11]:
optimizer = optim.SGD([Weight,bias],lr=0.01)

In [12]:
optimizer.zero_grad()

cost.backward()

optimizer.step()

7. 전체 코드 

In [13]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])


# 모델 초기화
W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

#optimizer 설정 
optimizer = optim.SGD([W,b],lr=0.01)

nb_epochs = 1999


for epoch in range(nb_epochs+1):

    #H(x)
    hypothesis = x_train * W + b

    #cost 계산 
    cost = torch.mean((hypothesis-y_train)**2) 

    #cost로 H(x)개선 
    optimizer.zero_grad()
    #역전파
    cost.backward()
    #진행
    optimizer.step()

    #100번마다 로그 출력
    if epoch%100 ==0:
        print('Epoch {:4d}/{} W: {:.3f}, b : {:.3f} Cost : {:.6f}'.format(epoch,nb_epochs,W.item(),b.item(),cost.item()))

Epoch    0/1999 W: 0.187, b : 0.080 Cost : 18.666666
Epoch  100/1999 W: 1.746, b : 0.578 Cost : 0.048171
Epoch  200/1999 W: 1.800, b : 0.454 Cost : 0.029767
Epoch  300/1999 W: 1.843, b : 0.357 Cost : 0.018394
Epoch  400/1999 W: 1.876, b : 0.281 Cost : 0.011366
Epoch  500/1999 W: 1.903, b : 0.221 Cost : 0.007024
Epoch  600/1999 W: 1.924, b : 0.174 Cost : 0.004340
Epoch  700/1999 W: 1.940, b : 0.136 Cost : 0.002682
Epoch  800/1999 W: 1.953, b : 0.107 Cost : 0.001657
Epoch  900/1999 W: 1.963, b : 0.084 Cost : 0.001024
Epoch 1000/1999 W: 1.971, b : 0.066 Cost : 0.000633
Epoch 1100/1999 W: 1.977, b : 0.052 Cost : 0.000391
Epoch 1200/1999 W: 1.982, b : 0.041 Cost : 0.000242
Epoch 1300/1999 W: 1.986, b : 0.032 Cost : 0.000149
Epoch 1400/1999 W: 1.989, b : 0.025 Cost : 0.000092
Epoch 1500/1999 W: 1.991, b : 0.020 Cost : 0.000057
Epoch 1600/1999 W: 1.993, b : 0.016 Cost : 0.000035
Epoch 1700/1999 W: 1.995, b : 0.012 Cost : 0.000022
Epoch 1800/1999 W: 1.996, b : 0.010 Cost : 0.000013
Epoch 1900/

optimizer.zero_grad()가 필요한 이유

In [14]:
import torch 
w = torch.tensor(2.0,requires_grad=True)


np_epochs=20
for epoch in range(nb_epochs+1):
    
    z = 2*w 
    z.backward() 
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0
수식을 w로 미분한 값 : 44.0
수식을 w로 미분한 값 : 46.0
수식을 w로 미분한 값 : 48.0
수식을 w로 미분한 값 : 50.0
수식을 w로 미분한 값 : 52.0
수식을 w로 미분한 값 : 54.0
수식을 w로 미분한 값 : 56.0
수식을 w로 미분한 값 : 58.0
수식을 w로 미분한 값 : 60.0
수식을 w로 미분한 값 : 62.0
수식을 w로 미분한 값 : 64.0
수식을 w로 미분한 값 : 66.0
수식을 w로 미분한 값 : 68.0
수식을 w로 미분한 값 : 70.0
수식을 w로 미분한 값 : 72.0
수식을 w로 미분한 값 : 74.0
수식을 w로 미분한 값 : 76.0
수식을 w로 미분한 값 : 78.0
수식을 w로 미분한 값 : 80.0
수식을 w로 미분한 값 : 82.0
수식을 w로 미분한 값 : 84.0
수식을 w로 미분한 값 : 86.0
수식을 w로 미분한 값 : 88.0
수식을 w로 미분한 값 : 90.0
수식을 w로 미분한 값 : 92.0
수식을 w로 미분한 값 : 94.0
수식을 w로 미분한 값 : 96.0
수식을 w로 미분한 값 : 98.0
수식을 w로 미분한 값 : 100.0
수식을