nn.Module로 구현하는 선형 회귀

nn.Linear() : 선형 회귀 모델을 구현함.

nn.functional.mse_loss() : 평균 제곱 오차

In [16]:
import torch 
import torch.nn as nn 
import torch.functional as F 
import torch.optim as optim 

In [17]:
torch.manual_seed(1)

In [27]:
x_train = torch.FloatTensor([ 
    [13,75,53,13],
    [66,23,15,77],
    [24,73,25,77]
])

y_train = torch.FloatTensor([ 
    [13],
    [24],
    [75]
])

In [28]:
model = torch.nn.Linear(4,1)

In [29]:
list(model.parameters())
#첫번째 값이 w이고, 두번째 값이 b 

[Parameter containing:
 tensor([[-0.0612,  0.1387,  0.0247,  0.1826]], requires_grad=True),
 Parameter containing:
 tensor([-0.1949], requires_grad=True)]

In [26]:
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)
np_epochs = 100

for epoch in range(np_epochs+1):

    prediction = model(x_train)

    cost = torch.nn.functional.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, np_epochs, cost.item()
      ))

Epoch    0/100 Cost: 1048.197266
Epoch  100/100 Cost: 47.592529


2. 다중 선형 회귀 구현

In [30]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

torch.manual_seed(1)

In [31]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [32]:
mymodel = nn.Linear(3,1) 

In [34]:
print(list(mymodel.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [36]:
optimizer = optim.SGD(mymodel.parameters(),lr=1e-5)

In [38]:
nb_epochs = 10000 

for epoch in range(nb_epochs+1):

    #hp
    prediction = mymodel(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()

    cost.backward()

    optimizer.step() 
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/10000 Cost: 31667.599609
Epoch  100/10000 Cost: 0.225988
Epoch  200/10000 Cost: 0.223909
Epoch  300/10000 Cost: 0.221935
Epoch  400/10000 Cost: 0.220059
Epoch  500/10000 Cost: 0.218270
Epoch  600/10000 Cost: 0.216571
Epoch  700/10000 Cost: 0.214954
Epoch  800/10000 Cost: 0.213418
Epoch  900/10000 Cost: 0.211954
Epoch 1000/10000 Cost: 0.210558
Epoch 1100/10000 Cost: 0.209230
Epoch 1200/10000 Cost: 0.207967
Epoch 1300/10000 Cost: 0.206767
Epoch 1400/10000 Cost: 0.205618
Epoch 1500/10000 Cost: 0.204524
Epoch 1600/10000 Cost: 0.203484
Epoch 1700/10000 Cost: 0.202488
Epoch 1800/10000 Cost: 0.201542
Epoch 1900/10000 Cost: 0.200637
Epoch 2000/10000 Cost: 0.199772
Epoch 2100/10000 Cost: 0.198950
Epoch 2200/10000 Cost: 0.198161
Epoch 2300/10000 Cost: 0.197412
Epoch 2400/10000 Cost: 0.196686
Epoch 2500/10000 Cost: 0.196001
Epoch 2600/10000 Cost: 0.195340
Epoch 2700/10000 Cost: 0.194717
Epoch 2800/10000 Cost: 0.194115
Epoch 2900/10000 Cost: 0.193538
Epoch 3000/10000 Cost: 0.192979
Epoc

In [39]:
print(list(mymodel.parameters()))

[Parameter containing:
tensor([[0.9751, 0.4822, 0.5515]], requires_grad=True), Parameter containing:
tensor([0.2848], requires_grad=True)]
