Tensor Manipulation

1. 뷰 == numpy.reshape 

파이토치 텐서의 뷰(.view)는 넘파이에서 reshape와 같은 역할을 합니다.

In [2]:
import numpy as np 
import torch 

In [3]:
t = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])

ft = torch.tensor(t)

In [4]:
print(t)
print(ft)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])


In [5]:
t = t.reshape(-1,16)
ft = ft.view(2,-1)

print(t)

[[1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]]


In [6]:
print(ft)

tensor([[1, 2, 3, 4, 2, 3, 4, 5],
        [3, 4, 5, 6, 4, 5, 6, 7]])


In [7]:
t = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
ft = torch.FloatTensor(t)

view는 reshape와 매우 흡사하다.

In [10]:
print(ft.view([-1,1,4]))
#3차원으로 변환
torch.Size([4,1,3])

tensor([[[1., 2., 3., 4.]],

        [[2., 3., 4., 5.]],

        [[3., 4., 5., 6.]],

        [[4., 5., 6., 7.]]])


torch.Size([4, 1, 3])

Squeeze() : 1에 해당하는 차원을 제거합니다.

In [15]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft.shape)
print(ft)

torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])


In [18]:
print(ft.squeeze())
ft = ft.squeeze()
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [21]:
test = torch.FloatTensor([[1,2,3],[2,3,4],[3,4,5]])
test = test.view([3,3,-1])
print(test.shape)

test = test.squeeze()
print(test.shape)

torch.Size([3, 3, 1])
torch.Size([3, 3])


Unsqueeze() - 특정 위치에 1인 차원을 추가합니다. 

언스퀴즈는 스퀴즈와 정반대입니다. 특정 위치에 1인 차원을 추가합니다. 

In [25]:
ft = torch.FloatTensor([0,1,2])
print(ft.shape)
print(ft)

torch.Size([3])
tensor([0., 1., 2.])


In [29]:
ft = ft.unsqueeze(0)
print(ft)
print(ft.shape)

#해당 인덱스에 1인 차원이 추가되었음을 알 수 있습니다.

tensor([[[[[0., 1., 2.]]]]])
torch.Size([1, 1, 1, 1, 3])


In [31]:
ft = torch.FloatTensor([0,1,2])
print(ft)
print(ft.shape)
ft = ft.unsqueeze(1)
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이렇게 view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서

모양과 차원을 조절합니다.

In [35]:
ft = torch.FloatTensor([0,1,2])
print(ft)
print(ft.shape)
ft = ft.squeeze()
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])


In [36]:
ft = torch.Tensor([[1,2,3],[2,3,4],[3,4,5]])

ft = ft.view(-1,9)
print(ft)
print(ft.shape)

ft = ft.squeeze()
print(ft)
print(ft.shape)


tensor([[1., 2., 3., 2., 3., 4., 3., 4., 5.]])
torch.Size([1, 9])
tensor([1., 2., 3., 2., 3., 4., 3., 4., 5.])
torch.Size([9])


타입 캐스팅



In [37]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [39]:
lt = lt.float()
print(lt)

tensor([1., 2., 3., 4.])


Byte 타입의 bt 텐서

In [44]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [45]:
bt2lt = bt.long()
bt2ft = bt.float()

print(bt2lt)
print(bt2ft)

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


연결하기(concatenate)

두 텐서를 연결합니다.

In [48]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [49]:
print(torch.cat([x,y],dim=0))
#0은 세로 기준으로 붙이기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [50]:
print(torch.cat([x,y],dim=1))
#1은 가로 기준으로 붙이기

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


스택킹


In [51]:
x= torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [53]:
print(x.shape)
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

torch.Size([2])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [54]:
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [55]:
print(torch.stack([x,y,z],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


ones_like, zero_like : 1로 채워진 텐서, 0으로 채워진 텐서

In [60]:
xx = np.ones((1,5)) #1*5의 2차원 넘파이 
print(xx)

yy = torch.ones((1,5))
print(yy)

zz = torch.ones_like((yy))
print(zz)

[[1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.]])


In [61]:
xx = np.zeros((1,5))
print(xx)
print(xx.shape)

yy = torch.zeros((1,5))
print(yy)
print(yy.shape)

zz = torch.zeros_like(yy)
print(zz)
print(zz.shape)

[[0. 0. 0. 0. 0.]]
(1, 5)
tensor([[0., 0., 0., 0., 0.]])
torch.Size([1, 5])
tensor([[0., 0., 0., 0., 0.]])
torch.Size([1, 5])


In-place Operation

In [64]:
x = torch.FloatTensor([[1,2],[3,4]])
x.shape


torch.Size([2, 2])

In [65]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.

view squeeze unsqueeze zero_like ones_like cat([x,y]) stack([x,y,z])

In [81]:
class Parent:

    def __init__(self,**kwargs):
        self.tensor1 = kwargs['tensor1']
        self.tensor2 = kwargs['tensor2']
    
    def show_tensor1(self):
        print('From Parent : ')
        print(self.tensor1)
    def show_tensor2(self):
        print('From Parent : ')
        print(self.tensor2)


#view, #squeeze, #unsqueeze, #concat, #stack을 모두 가지고 있는 클래스 

In [85]:
class Child(Parent):

    def __init__(self,**kwargs):
        
        self.tensor1 = kwargs["tensor1"]
        self.tensor2 = kwargs["tensor2"]
        
        super(Child,self).__init__(tensor1 = self.tensor1,tensor2=self.tensor2)


    def my_squeeze(self):
        print('current :',self.tensor1,self.tensor1.shape)
        tmptensor = self.tensor1.squeeze()
        print('after :',tmptensor,tmptensor.shape)
    

    def my_concat_zero(self,input):
        res = torch.cat([self.tensor1,self.tensor2,input],dim=0)
        return res

    def my_concat_one(self,input):
        res = torch.cat([self.tensor1,self.tensor2,input],dim=1)
        return res

        

In [86]:
x = Child(tensor1 = torch.FloatTensor([[1,2,3],[4,5,6]]), tensor2 = torch.FloatTensor([[3,2,1,],[6,5,4]]))
res= x.my_concat_zero(torch.FloatTensor([[1,2,3],[4,5,6]]))
x.show_tensor1()
x.show_tensor2()


From Parent : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
From Parent : 
tensor([[3., 2., 1.],
        [6., 5., 4.]])


In [87]:
res2 = x.my_concat_one(torch.FloatTensor([[15,24,13],[36,13,23]]))
print(res2)

tensor([[ 1.,  2.,  3.,  3.,  2.,  1., 15., 24., 13.],
        [ 4.,  5.,  6.,  6.,  5.,  4., 36., 13., 23.]])
