다중 선형 회귀

H(x) = w1 * x1 + w2 * x2 + w3 * x3 +b

파이토치로 구현하기

In [1]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

In [2]:
torch.manual_seed(1)

1. 훈련 데이터

In [3]:
x1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

2. 가중치와 편향 선언 

In [ ]:
#가중치 w와 편향 b 초기화 
w1 = torch.zeros(1,requires_grad=True)
w2 = torch.zeros(1,requires_grad=True)
w3 = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

3. optimizer, hypothesis를 선언

In [6]:
optimizer = optim.SGD([w1,w2,w3,b],lr=1e-5)

nb_epochs = 1000


for epoch in range(nb_epochs+1):

    # H(x) 계산 
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b 

    # cost 계산 
    cost = torch.mean((hypothesis-y_train)**2)

    # cost로 H(x)를 개선 
    optimizer.zero_grad() 
    cost.backward()
    optimizer.step() 

    # 100번마다 로그 출력 
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} w1 : {:.3f} w2 : {:.3f} w3 : {:.3f} b : {:.3f} Cost : {:.6f}'.format(epoch,nb_epochs,w1.item(),w2.item(),w3.item(),b.item(),cost.item()))

Epoch    0/1000 w1 : 0.294 w2 : 0.294 w3 : 0.593 b : 0.003 Cost : 29661.800781
Epoch  100/1000 w1 : 0.335 w2 : 0.328 w3 : 0.672 b : 0.004 Cost : 0.349551
Epoch  200/1000 w1 : 0.337 w2 : 0.325 w3 : 0.672 b : 0.004 Cost : 0.333070
Epoch  300/1000 w1 : 0.339 w2 : 0.322 w3 : 0.673 b : 0.004 Cost : 0.317483
Epoch  400/1000 w1 : 0.340 w2 : 0.318 w3 : 0.674 b : 0.004 Cost : 0.302755
Epoch  500/1000 w1 : 0.342 w2 : 0.315 w3 : 0.674 b : 0.004 Cost : 0.288815
Epoch  600/1000 w1 : 0.344 w2 : 0.312 w3 : 0.675 b : 0.004 Cost : 0.275641
Epoch  700/1000 w1 : 0.346 w2 : 0.309 w3 : 0.676 b : 0.004 Cost : 0.263198
Epoch  800/1000 w1 : 0.347 w2 : 0.306 w3 : 0.676 b : 0.004 Cost : 0.251418
Epoch  900/1000 w1 : 0.349 w2 : 0.303 w3 : 0.677 b : 0.004 Cost : 0.240283
Epoch 1000/1000 w1 : 0.351 w2 : 0.301 w3 : 0.677 b : 0.004 Cost : 0.229765


In [7]:
print(w1)

tensor([0.3507], requires_grad=True)


In [12]:
print(w1.item())
print(type(w1))

0.35071635246276855
<class 'torch.Tensor'>


행렬 연산을 고려하여, 파이토치로 구현

In [22]:
import numpy as np
x_train = torch.FloatTensor([[73,80,75],
    [93,88,93],
    [89,91,80],
    [96,98,100],
    [73,66,70]])


y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [20]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [17]:
w = torch.FloatTensor([[1],[1],[1]])
print(w.shape)
print(w)

torch.Size([3, 1])
tensor([[1.],
        [1.],
        [1.]])


In [18]:
w = torch.zeros((3,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [21]:
optimizer = optim.SGD([w,b],lr=1e-5)

In [27]:
nb_epochs = 1000

for epoch in range(nb_epochs+1):

    #가설 
    hypothesis = x_train.matmul(w)+b

    #hypothesis에 대한 비용 
    cost = torch.mean((hypothesis-y_train)**2)

    #cost로 H(x)계산 
    #초기화
    optimizer.zero_grad()

    cost.backward()

    optimizer.step()

    print('Epoch {:4d}/{} hypothesis : {} cost : {:.6f}'.format(epoch,nb_epochs,hypothesis.squeeze().detach(),cost.item()))

Epoch    0/1000 hypothesis : tensor([0., 0., 0., 0., 0.]) cost : 29661.800781
Epoch    1/1000 hypothesis : tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) cost : 9537.694336
Epoch    2/1000 hypothesis : tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) cost : 3069.590820
Epoch    3/1000 hypothesis : tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) cost : 990.670288
Epoch    4/1000 hypothesis : tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) cost : 322.481964
Epoch    5/1000 hypothesis : tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) cost : 107.717064
Epoch    6/1000 hypothesis : tensor([148.9423, 178.9731, 169.8976, 192.0301, 136.5279]) cost : 38.687401
Epoch    7/1000 hypothesis : tensor([151.1574, 181.6347, 172.4254, 194.8856, 138.5585]) cost : 16.499046
Epoch    8/1000 hypothesis : tensor([152.4131, 183.1435, 173.8590, 196.5042, 139.7097]) cost : 9.365656
Epoch    9/1000 hypothesis : tensor([153.1250, 183.9988, 174.6723, 197.4216, 140.

내맘대로 만들어볼꺼야.

In [28]:
import torch 
import torch.nn as nn 
import torch.functional as F 
import torch.optim as optim 


In [29]:
x_train = torch.FloatTensor([
    [13,72,15,24,22],
    [66,14,86,53,18],
    [15,24,17,98,13],
    [13,66,113,97,35],
    [13,24,76,76,15]
])

y_train = torch.FloatTensor([ 
    [152],
    [132],
    [142],
    [463],
    [664]    
])

In [30]:
w= torch.zeros((5,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)


In [31]:
#최적화 객체 생성 
optimizer = optim.SGD([w,b],lr = 1e-5)


print(w)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], requires_grad=True)


In [32]:
epochs=1000

for epoch in range(epochs+1):

    #hypothesis 
    hypothesis = x_train * w + b 

    cost = torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward() 
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/1000 hypothesis: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) Cost: 143191.406250
Epoch    1/1000 hypothesis: tensor([[ 0.2370,  1.2845,  0.2725,  0.4323,  0.3968],
        [ 1.6580,  0.3566,  2.1586,  1.3327,  0.4567],
        [ 0.2908,  0.4615,  0.3287,  1.8654,  0.2528],
        [ 1.5663,  7.9268, 13.5673, 11.6471,  4.2065],
        [ 1.4150,  2.6070,  8.2419,  8.2419,  1.6317]]) Cost: 140465.500000
Epoch    2/1000 hypothesis: tensor([[ 0.4727,  2.5620,  0.5435,  0.8623,  0.7914],
        [ 3.2959,  0.7089,  4.2910,  2.6492,  0.9079],
        [ 0.5790,  0.9190,  0.6546,  3.7145,  0.5035],
        [ 3.0977, 15.6766, 26.8314, 23.0340,  8.3191],
        [ 2.8157,  5.1878, 16.4012, 16.4012,  3.2470]]) Cost: 137828.406250
Epoch    3/1000 hypothesis: tensor([[ 0.7072,  3.8328,  0.8131,  1.2899,  1.1839],
        [ 4.9141,  1.0569,  6.3976,  3.9498,  1.3536],
        [ 0.864